version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/vscode-styled-jsx-syntax'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/vscode-styled-jsx-languageserver'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/vscode-styled-jsx-languageserver/client'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/vscode-styled-jsx-languageserver/server'
    schedule:
      interval: 'daily'
